import React from "react";

interface SignatureProps {
  name: string;
  title?: string;
  company?: string;
}

export default function Signature({ name, title, company }: SignatureProps) {
  return (
    <div className="p-4 border border-gray-300 rounded-lg bg-white shadow-sm hover:shadow-md transition-shadow">
      <div className="font-bold text-lg text-[#8B4513]">{name}</div>
      {title && <div className="text-gray-600 text-sm">{title}</div>}
      {company && <div className="text-gray-500 text-xs mt-1">{company}</div>}
      <div className="mt-2 pt-2 border-t border-gray-200 italic text-sm text-gray-400">
        Generated by SigGen
      </div>
    </div>
  );
} 